apiVersion: v1
kind: Service
metadata:
  name: weather-service-service
spec:
  type: ClusterIP
  selector:
    app: weather-service
  ports:
    - name: weather-service-port
      protocol: TCP
      port: 8082
      targetPort: 8080