apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - name: client-port
      protocol: TCP
      port: 8080
      targetPort: 8080