apiVersion: v1
kind: Service
metadata:
  name: generator-service
spec:
  type: LoadBalancer
  selector:
    app: generator
  ports:
    - name: generator-port
      protocol: TCP
      port: 8081
      targetPort: 8080