apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: LoadBalancer
  selector:
    app: kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-metrics
      protocol: TCP
      port: 3030
      targetPort: 3030
    - name: zookeeper
      protocol: TCP
      port: 2181
      targetPort: 2181